### ISSUE TITLE
R.h not found

### ISSUE THREAD

**Issue by gdkrmr** [nullsatz/gputools#15]
installation on Ubuntu 14.04 tries to use `/usr/lib/R/include` for the header files, but the header files are under `/usr/share/R/include`.

A save way of finding the location of header files in R is `R CMD config --cppflags`, I think.

**Comment by wush978** [comment]
For a workaround, we could install the package via command: `install.packages("gputools", configure.args = "--with-r-include=/usr/share/R/include")` to resolve header not found error.

But I think the suggestion above is a better solution.
